Outliers
ngood13/stoves_nih_2016_git pull request #88
Opened 2017-02-17 21:06 UTC by KFedak

taking a break so pulling my branch changes to master. Will pick up later today or tomorrow by first pushing from master to my branch again.

2017-02-17 21:12 UTC, kbilsback commented
:octocat:

2017-02-17 21:13 UTC, kbilsback commented
yea! emojis 🌵 😸 :taco:

2017-02-17 21:46 UTC, kbilsback requested changes
Wait, how did those benzene and toluene files sneak in there? #roguemerge 😸

2017-02-17 21:50 UTC, KFedak commented
waaaaa I have no idea! :crying_cat_face:

2017-02-17 21:52 UTC, ngood13 approved these changes
just make sure my commits are part of the merge to the master...

2017-02-17 21:52 UTC, ngood13 commented on r_markdown/benzene_emissionsfactor_qa.Rmd
> +             dplyr::left_join(fuel_burnt, by = "id")
both samples and fuel_burnt have a variable called "fuel" which is causing problems when you join (creates a variable fuel.x and then issues with your code does the line). I've fixed in commit...

2017-02-17 21:52 UTC, ngood13 commented on r_markdown/benzene_emissionsfactor_qa.Rmd
> +---
I'll apply the new style template to this in a new branch after we've merged...

2017-02-17 21:52 UTC, ngood13 commented on r_markdown/process_metadata.Rmd
>    save(batch_times, file="../r_files/batch_times.Rda")
looks good

2017-02-17 21:52 UTC, ngood13 commented on r_markdown/toluene_emissionsfactor_qa.Rmd
> +  ggtitle("Benzene EFs by Stove Type - Wood Stoves Only") +
Benzene or Toluene?

2017-02-17 21:52 UTC, ngood13 commented on r_markdown/toluene_emissionsfactor_qa.Rmd
> +  ggtitle("Benzene EFs by Stove Type - Charcoal Stoves Only") +
Benzene or Toluene?

2017-02-17 21:52 UTC, ngood13 commented on r_markdown/toluene_emissionsfactor_qa.Rmd
> +```{r, echo=FALSE, warning=FALSE, message=FALSE, results='markup', cache=FALSE, fig.width = 10}
drop x axis labels perhaps?

2017-02-17 21:52 UTC, ngood13 commented on r_markdown/toluene_emissionsfactor_qa.Rmd
> +
I'll add some ## when I do the style update for ease of navigation...

2017-02-17 21:52 UTC, ngood13 commented on r_markdown/benzene_emissionsfactor_qa.Rmd
> +# Plots
see comments on toluene that are also relevant to these (and visa versa...)

2017-02-17 21:52 UTC, ngood13 commented on r_markdown/benzene_emissionsfactor_qa.Rmd
> +  ggtitle("Benzene EFs by Stove and Fuel categories") +
we should define a manual fuel color-scale so they always appear the same regardless of subsetting (Kelsey? 👍 )

2017-02-17 21:52 UTC, ngood13 commented on r_markdown/toluene_emissionsfactor_qa.Rmd
> +---
same as benzene (fuel conflict, fixed)

2017-02-17 21:57 UTC, kbilsback commented on r_markdown/process_metadata.Rmd
> +Outlier 16B checked by KF in February 2017. There is no transcription error, but this measure is QC-flagged as bad due to an issue with the carbonyl line being clogged/having known sampling issues th
Nice! Comments!

2017-02-18 23:38 UTC, KFedak commented
I finished making my comments in the "process_metadata.Rmd" file, and am now trying to merge back to the master.... but it looks like merging is blocked until a requested change is addressed, and I am blocked from making that change?

2017-02-19 18:18 UTC, ngood13 commented
Looks @kbilsback has requested changes, not sure who they are, they sound like trouble :-)

Also, I fixed some stuff in the voc markdowns that @rowdyspecialkbnewlyreformedenforcerofrules deleted, so you might want to look back and find them if needed...

2017-02-19 18:55 UTC, kbilsback approved these changes

2017-02-19 18:55 UTC, kbilsback commented
@KFedak already fixed the changes! :octocat: 👍

2017-02-19 20:48 UTC, merged